import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Layout from '@/components/Layout'
import { useEffect, useState, useRef } from 'react'
import { getTrendings, rightPagination } from "../functions/MDB"
import Image from 'next/image'
export default function Home() {
  const dataFetchedRef = useRef(false);
  const [user, setUser] = useState(null);;
  const [trendingMovies, setTrendingMovies] = useState({ slice: 0, data: [] })
  const [trendingSeries, setTrendingSeries] = useState({ slice: 0, data: [] })
  useEffect(() => {
    if (dataFetchedRef.current) return;
    const user = JSON.parse(localStorage.getItem('user'))
    if (user) {
      setUser(user)
    }

    getTrendings(setTrendingMovies, setTrendingSeries)



    // dataFetchedRef.current = true;
  }, []);
  return (
    <>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Layout user={user} setUser={setUser}>
          <div style={{ height: "100vh" }}>
            <button onClick={() => rightPagination()} style={{ fontSize: "40px", background: "black" }}>{"<"}</button>
            <button onClick={() => rightPagination(trendingMovies, setTrendingMovies)} style={{ fontSize: "40px", background: "black" }}>{">"}</button>
            {trendingMovies.slice}
            {trendingMovies.data.map(e => <Image
              src={"https://image.tmdb.org/t/p/original" + e.poster_path}
              alt="Picture of the author"
              width={100}
              height={200}
            />)}
          </div>

        </Layout>
      </main>
    </>
  )
}
