import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Layout from '@/components/Layout'
import { useEffect, useState, useRef } from 'react'

export default function Home() {
  const dataFetchedRef = useRef(false);

  const [user, setUser] = useState(null)
  useEffect(() => {
    if (dataFetchedRef.current) return;
    const user = JSON.parse(localStorage.getItem('user'))
    if (user) {
      setUser(user)
    }

    console.log("useeffect")



    // dataFetchedRef.current = true;
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Layout user={user} setUser={setUser}>
          <div style={{ height: "100vh" }}>qsd</div>
        </Layout>
      </main>
    </>
  )
}
